### ISSUE TITLE
sane defaults - sv_round_stats_format

### ISSUE THREAD

**Issue by jxsl13** [ZillyInsta/ddnet-insta#101]
Please change the default value of sv_round_stats_format to 2 which should be the one that is most commonly used.

```
0=csv 1=psv 2=ascii(default) table 3=markdown table 4=json
```

**Comment by ChillerDragon** [comment]
Ascii table is unfinished I think. You probably meant the format [lukure](https://github.com/ZillyInsta/ddnet-insta/issues/90#issuecomment-1931916789) requested. I called that one psv.

Pipe separated values :sweat_smile:
