### ISSUE TITLE
🐛 Flag "laggs" behind

### ISSUE THREAD

**Issue by AssassinTee** [ZillyInsta/ddnet-insta#6]
Flag "laggs" behind

## Images
![screenshot_2021-11-18_16-25-16](https://user-images.githubusercontent.com/821401/142446323-081c63a8-f0c3-42db-b3c7-4435ec42e1c2.png)

## System
Windows 10
Default 0.7.5 Steam Client
FPS: All of them

**Comment by ChillerDragon** [comment]
Can not reproduce on ZillyWoods or ddnet on my linux -.-

**Comment by ChillerDragon** [comment]
I still can not reproduce. I did some changes to the flag snapping. Could you please check again if it is fixed.
If you are too lazy to spin up a server you can test it on mine 149.202.127.134:8707

**Comment by AssassinTee** [comment]
While the ping is awefull on this server, I couldn't reproduce this anymore. I was also checking if any prediction settings may break this.

**Comment by ChillerDragon** [comment]
Ah nice I can now reproduce. I was testing it wrong. It has to be another tee for the flag to lagg behind. Its smooth when your own tee is the flag carrier.

Thanks for testing it again and the useful screenshots! Will give this another shot now that I can reproduce it! :heart:

**Comment by ChillerDragon** [comment]
Okay I finally found a hacky fix. Not sure what caused the issue but it should be solved now.
Also I noticed that the client side setting `cl_predict_players 1` fixes it as well without need to change the server.
