### ISSUE TITLE
Server config option to hide admins

### ISSUE THREAD

**Issue by jxsl13** [ZillyInsta/ddnet-insta#68]
Add a server config option that allows to toggle whether the server sends or hides the admin highlighting for all non-admin (helper/mod) players 

Admins/mods/helpers should still be able to see each other.

**Comment by ChillerDragon** [comment]
Wishes for the setting name?

**Comment by jxsl13** [comment]
sv_hide_admins

**Comment by jxsl13** [comment]
do admins and mods still see each other when logged in :0?

**Comment by jxsl13** [comment]
noice
