### ISSUE TITLE
Add an automatic timer for ready mode pauses

### ISSUE THREAD

**Issue by lukure** [ZillyInsta/ddnet-insta#76]
5 min would be a good setting

**Comment by ChillerDragon** [comment]
I am not sure I understand what you mean.

You mean a paused game should automatically unpause after 5 minutes? Why not wait for all to press ready?

**Comment by lukure** [comment]
Yes, that's exactly what I meant. On the one hand, we need this in every tournament, there is always a time limit of max. 5 min allowed (shorter of course still possible) and also in open rounds this is actually quite nice, because people just disappear for 20 min from time to time and as long as nobody can do anything with the server.
If it really had to be longer then the mates could simply take another break, but normally the person is completely out of action and has to be replaced.

**Comment by ChillerDragon** [comment]
Ah for tournaments that makes sense. For normal games seems weird to force continue the game when someone is afk :D in that case a spec vote should maybe be more useful.

But yea I will add it.

**Comment by lukure** [comment]
Yes, but spec votes don't work during a break, so maybe that would also be an approach to change that.

**Comment by ChillerDragon** [comment]
> Yes, but spec votes don't work during a break, so maybe that would also be an approach to change that.

Might be annoying to fix but seems like a bug indeed

**Comment by jxsl13** [comment]
who can spec vote then? Other players that are ingame, spectators, moderators ?

**Comment by ChillerDragon** [comment]
> who can spec vote then? Other players that are ingame, spectators, moderators ? Everyone?

Ideally everyone. If allow spec votes is on spectators should be able to vote in game players during a pause.

If there is one person afk camping alone in a paused game the server is basically locked down. That is bad. So spectators should be able to vote this player (given spec voting is active).

BTW this topic moved to the new issue here https://github.com/ZillyInsta/ddnet-insta/issues/78

**Comment by ChillerDragon** [comment]
You can now set ``sv_force_ready_all 5`` to force unpause after 5 minutes. Set it to ``0`` to allow infinite pause again (which is the default). There will be a warning printed in chat 1 minute and 10 seconds before the force unpause happens.

**Comment by lukure** [comment]
Sounds very good, I'll have to have another look at how exactly it works ingame :D
