### ISSUE TITLE
timelimit crashes the server

### ISSUE THREAD

**Issue by lukure** [ZillyInsta/ddnet-insta#84]

**Comment by lukure** [comment]
Have you changed anything? I restarted the server and it's working again.

**Comment by ChillerDragon** [comment]
nope but im pretty sure its the asan that is not active on all servers and its all the same issue. I had no time to look into it yet.

**Comment by lukure** [comment]
a ok

**Comment by ChillerDragon** [comment]
Likely a duplicate of https://github.com/ZillyInsta/ddnet-insta/issues/80
