### ISSUE TITLE
single player in team red or blue not being reported to the master servers

### ISSUE THREAD

**Issue by jxsl13** [ZillyInsta/ddnet-insta#85]
When a single player with a score of 0 joins either blue or red, then the master server does not seem to get an update of that team switch from spec to either one of those teams.

I guess, score changes trigger a master server update, a team switch does not.

**Comment by ChillerDragon** [comment]
Should be fixed. Could you verify it works for you? :)

**Comment by jxsl13** [comment]
will test after work

**Comment by jxsl13** [comment]
fixed
