### ISSUE TITLE
Votes with custom ddnet-insta commands are skipped on first load

### ISSUE THREAD

**Issue by ChillerDragon** [ZillyInsta/ddnet-insta#88]
The vote list is loaded and validated before the instagib controller registers its commands. So on first load they are skipped. If the votes are then registered a second time it works just fine.

https://github.com/ZillyInsta/cfg/pull/3#issuecomment-1899952540

**Comment by ChillerDragon** [comment]
"fixed" for now. But the hack is so ugly I would like to keep this issue open until the upstream discussions are finished. If ddnet decides to support registering commands in the game controllers in https://github.com/ddnet/ddnet/issues/7777. Adding votes and running commands from the game controller on first autoexec load should be supported in ddnet. If ddnet decides against we might either not register our commands in the game controller at all. Or are forced to create git conflict surface to fix it.

**Comment by gerdoe-jr** [comment]
This fix segfaults server on any setting change after boot. Deleted the `autoexec` executing totally, works fine

**Comment by ChillerDragon** [comment]
Moved all commands back to gamecontext so this should be working as expected now.
