### ISSUE TITLE
smart spec chat

### ISSUE THREAD

**Issue by lukure** [ZillyInsta/ddnet-insta#89]
once you have activated it, you can no longer deactivate it

**Comment by ChillerDragon** [comment]
You mean ``sv_tournament_chat_smart`` the note says "Turns sv_tournament_chat on on restart and off on round end (1=specs,2=all)". You have to leave it on until your desired state is reached after round restart for example and then turn it off. Applying that change instantly would be nice yes but I do not know what the desired state is. Basically it manages the other config ``sv_tournament_chat`` for you. So you should be able to turn it off manually by doing

```
sv_tournament_chat_smart 0;sv_tournament_chat 0;
```

Its hard to guess which state the user wants ``sv_tournament_chat`` in if the ``sv_tournament_chat_smart`` is turned off.
Assuming its also off might also be misleading. Storing the previous state seems also messy. Not sure what would be a clean solution here. I am leaning towards doing nothing or maybe just showing a warning in rcon saying

"Warning: sv_tournament_chat is still set to 1. Set it to 0 if you want to turn it off"

**Comment by lukure** [comment]
Yes, that's perfect!
