### ISSUE TITLE
Post round end result to discord via webhook

### ISSUE THREAD

**Issue by ChillerDragon** [ZillyInsta/ddnet-insta#90]
Similar to the client side auto statboard screenshot. The server should have a way to capture round results. Ideally the user can choose a format and a upload destination.

formats:
- json
- csv
- human friendly table plaintext ascii
- human friendly table markdown
- psv (pipe separated values lukure requested)

<details>

```
---> Server: gCTF Server #4, Map: ctf2, Gametype: gCTF+.
(Length: 13 min 24.10 sec)
 
**Red Team:**
ID: 0 | Name: smurf | Score: 50 | Kills: 39 | Deaths: 52 | Ratio: 0.75
ID: 1 | Name: samii | Score: 76 | Kills: 54 | Deaths: 69 | Ratio: 0.78
ID: 2 | Name: pridy | Score: 39 | Kills: 35 | Deaths: 64 | Ratio: 0.55
ID: 7 | Name: PɦnX | Score: 67 | Kills: 58 | Deaths: 89 | Ratio: 0.65
ID: 13 | Name: PŁ∂עfά¥e | Score: 79 | Kills: 68 | Deaths: 59 | Ratio: 1.15
**Blue Team:**
ID: 3 | Name: TNT | Score: 103 | Kills: 74 | Deaths: 50 | Ratio: 1.48
ID: 4 | Name: Sneak | Score: 79 | Kills: 59 | Deaths: 40 | Ratio: 1.48
ID: 6 | Name: jeti | Score: 101 | Kills: 78 | Deaths: 61 | Ratio: 1.28
ID: 8 | Name: KIRA | Score: 74 | Kills: 64 | Deaths: 51 | Ratio: 1.25
ID: 9 | Name: rqza | Score: 88 | Kills: 54 | Deaths: 59 | Ratio: 0.92
---------------------
**Red: 119 | Blue 1023**
```

</details>

destinations:
- local disk (could be served by a webserver then)
- post to discord webhook

**Comment by lukure** [comment]
Discord Design example:
**Red Team:**
ID: 0 | Name: smurf | Score: 50 | Kills: 39 | Deaths: 52 | Ratio: 0.75
ID: 1 | Name: samii | Score: 76 | Kills: 54 | Deaths: 69 | Ratio: 0.78
ID: 2 | Name: pridy | Score: 39 | Kills: 35 | Deaths: 64 | Ratio: 0.55
ID: 7 | Name: PɦnX | Score: 67 | Kills: 58 | Deaths: 89 | Ratio: 0.65
ID: 13 | Name: PŁ∂עfά¥e | Score: 79 | Kills: 68 | Deaths: 59 | Ratio: 1.15
**Blue Team:**
ID: 3 | Name: TNT | Score: 103 | Kills: 74 | Deaths: 50 | Ratio: 1.48
ID: 4 | Name: Sneak | Score: 79 | Kills: 59 | Deaths: 40 | Ratio: 1.48
ID: 6 | Name: jeti | Score: 101 | Kills: 78 | Deaths: 61 | Ratio: 1.28
ID: 8 | Name: KIRA | Score: 74 | Kills: 64 | Deaths: 51 | Ratio: 1.25
ID: 9 | Name: rqza | Score: 88 | Kills: 54 | Deaths: 59 | Ratio: 0.92
---------------------
**Red: 119 | Blue 1023**

**Comment by lukure** [comment]
The github formation didn't go quite right ;D
Red Team:, Blue Team: and Red: 119 | Blue 1023 should be in thick letters!

**Comment by ChillerDragon** [comment]
Ye that part is already done

**Comment by lukure** [comment]
O nice, havent noticed

**Comment by ChillerDragon** [comment]
The posting to discord is done. The csv, json and file stuff is more a work in progress but I will close the issue now until someone actually needs it.
